### ISSUE TITLE
Question: Is it enough to have this mod on the server?

### ISSUE THREAD

**Issue by shyim** [JoelOliMclean/NoRainDamage#1]
Hey,
Is it enough to have this mod on the server?

Thanks for building this :)

**Comment by JoelOliMclean** [comment]
Hey @shyim !

Due to the nature of how the rain damage is calculated, unfortunately it won't work just having it on the server.

The way the game works, at any one time in a server, an object belongs to 1 player and that player's game is used to calculate rain damage. I'd recommend if you're on a server with people you know, asking them all to install the mod, otherwise when they're in range of your buildings there's a chance the mod will not work.

Thanks for using the mod if you are! 😄

**Comment by JoelOliMclean** [comment]
Hey @shyim !

Due to the nature of how the rain damage is calculated, unfortunately it won't work just having it on the server.

The way the game works, at any one time in a server, an object belongs to 1 player and that player's game is used to calculate rain damage. I'd recommend if you're on a server with people you know, asking them all to install the mod, otherwise when they're in range of your building's there's a chance the mod will not work.

Thanks for using the mod if you are! 😄

**Comment by shyim** [comment]
We have one friend playing on Geforce Now. We will try how good it works when one player doesn't have any mods :D
